"""FastAPI service for interactively testing a trained Zipformer checkpoint.

Wraps the same load/decode path as transcribe.py behind a small HTTP API with
autogenerated Swagger docs at /docs, so a checkpoint can be poked with real
audio uploads instead of only via corpus-manifest eval.py runs.

Config is read from ZIPFORMER_CONFIG (default: config.rtx5080.yaml). That
file's manifests.output_dir is an absolute path, so unlike train.py/eval.py
this has no CWD dependency - run it from anywhere.

Usage:
    python serve.py                          # http://127.0.0.1:8000/docs
    ZIPFORMER_MODEL=path/to/other.pt python serve.py
    ZIPFORMER_DEVICE=cuda python serve.py     # only once the GPU has headroom -
                                               # defaults to cpu so this never
                                               # competes with a live training run
"""

import os
import tempfile
from pathlib import Path
from typing import Union

import torch
from fastapi import FastAPI, File, HTTPException, UploadFile
from pydantic import BaseModel

from eval import checkpoint_uses_rnnt, decode_batch
from src.config import load_sections
from src.model import ZipformerFromScratch
from tokenizer import BPETokenizer
from transcribe import chunk_waveform, load_audio

CONFIG_PATH = os.environ.get("ZIPFORMER_CONFIG", "config.rtx5080.yaml")
DEVICE = torch.device(os.environ.get("ZIPFORMER_DEVICE", "cpu"))

manifests_args = load_sections(CONFIG_PATH, "manifests")
model_args = load_sections(CONFIG_PATH, "model")
output_dir = Path(manifests_args.output_dir)
MODEL_PATH = Path(os.environ.get("ZIPFORMER_MODEL", str(output_dir / "best.pt")))
TOKENIZER_PATH = output_dir / "tokenizer.model"

for path in (MODEL_PATH, TOKENIZER_PATH):
    if not path.exists():
        raise SystemExit(f"Not found: {path}")

tokenizer = BPETokenizer.load(str(TOKENIZER_PATH))
_checkpoint = torch.load(MODEL_PATH, map_location="cpu", weights_only=False)
_state_dict = _checkpoint.get("model_state_dict", _checkpoint)
USE_RNNT = checkpoint_uses_rnnt(_state_dict)
model = ZipformerFromScratch(
    vocab_size=tokenizer.vocab_size,
    d_model=model_args.d_model,
    n_layers=model_args.n_layers,
    n_heads=model_args.n_heads,
    attn_head_dim=model_args.attn_head_dim,
    nla_hidden_dim=model_args.nla_hidden_dim,
    conv_kernel_size=model_args.conv_kernel_size,
    ff_expansion_factor=model_args.ff_expansion_factor,
    dropout=model_args.dropout,
    bypass_min_scale=model_args.bypass_min_scale,
    use_rnnt=USE_RNNT,
)
model.load_state_dict(_state_dict, strict=True)
model.to(DEVICE).eval()

app = FastAPI(
    title="Zipformer ASR (Bengali)",
    description="Interactive test endpoint for a trained Zipformer checkpoint (CTC or RNNT, detected from its weights).",
    version="0.1.0",
)


class TranscribeResponse(BaseModel):
    filename: str
    duration_seconds: float
    num_chunks: int
    chunks: list[str]
    transcript: str


class HealthResponse(BaseModel):
    status: str
    checkpoint: str
    epoch: Union[int, str]
    step: Union[int, str]
    vocab_size: int
    device: str
    decoder: str


@app.get("/health", response_model=HealthResponse)
def health():
    return HealthResponse(
        status="ok",
        checkpoint=str(MODEL_PATH),
        epoch=_checkpoint.get("epoch", "?"),
        step=_checkpoint.get("step", "?"),
        vocab_size=tokenizer.vocab_size,
        device=str(DEVICE),
        decoder="rnnt" if USE_RNNT else "ctc",
    )


@app.post("/transcribe", response_model=TranscribeResponse)
async def transcribe_endpoint(
    audio: UploadFile = File(..., description="Any format soundfile can read (wav, flac, ogg, ...)"),
    chunk_seconds: float = 15.0,
    overlap_seconds: float = 0.0,
):
    suffix = Path(audio.filename or "audio").suffix or ".wav"
    with tempfile.NamedTemporaryFile(suffix=suffix) as tmp:
        tmp.write(await audio.read())
        tmp.flush()
        try:
            waveform, duration = load_audio(tmp.name)
        except Exception as exc:
            raise HTTPException(status_code=400, detail=f"Could not read audio: {exc}")

    chunks = chunk_waveform(waveform, chunk_seconds, overlap_seconds)
    pieces = []
    with torch.no_grad():
        for chunk in chunks:
            batch = chunk.unsqueeze(0).to(DEVICE)
            lengths = torch.tensor([chunk.numel()], device=DEVICE)
            pieces.append(decode_batch(model, batch, lengths, tokenizer)[0])

    return TranscribeResponse(
        filename=audio.filename or "audio",
        duration_seconds=round(duration, 3),
        num_chunks=len(chunks),
        chunks=pieces,
        transcript=" ".join(p for p in pieces if p).strip(),
    )


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=int(os.environ.get("PORT", 8001)))
